### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by s-pellegrini** [yushih/solidity-gas-profiler#3]
It looks like this project is still missing a licence, making it de-facto not open source. Would you consider adding one?

**Comment by yushih** [comment]
@s-pellegrini thanks for pointing it out. Could you please make a PR for the license? Thanks.

**Comment by s-pellegrini** [comment]
Well, I could. But I don't know what licence you want to have.

Also usually a licence header is added to every file, not sure it makes sense for a complete newbie in the broject to change every single file in a commit. But you could also just add a LICENCE file, it really depends on your choice.

**Comment by yushih** [comment]
Just adopted MIT.

**Comment by s-pellegrini** [comment]
Nice!
